class Autogenerated {
 late bool status;
 late String message;
 // late List<List> list;



  Autogenerated.fromJson(Map<String, dynamic> json) {
    status = json['status'];
    message = json['message'];
    // if (json['list'] != null) {
    //   list =  List<List>();
    //   json['list'].forEach((v) {
    //     list.add( List.fromJson(v));
    //   });
    // }
  }

}

// class List {
//   int id;
//   String questionEn;
//   String questionAr;
//   String answerEn;
//   String answerAr;
//
//
//   List.fromJson(Map<String, dynamic> json) {
//     id = json['id'];
//     questionEn = json['question_en'];
//     questionAr = json['question_ar'];
//     answerEn = json['answer_en'];
//     answerAr = json['answer_ar'];
//   }
//
//
// }